### ISSUE TITLE
PHP for Beginners

### ISSUE THREAD

**Issue by pernillasterner** [pernillasterner/php_note_app#1]
## Description

PHP course for beginners. The instructor is [Jeffrey Way](https://laracasts.com/browse/instructors/JeffreyWay)

Link to the course -> [PHP for Beginners](https://laracasts.com/series/php-for-beginners-2023-edition)

#### Content 👇

- [x] pernillasterner/php_fundamentals#3
- [x] pernillasterner/php_fundamentals#2
- [x] pernillasterner/php_note_app#4 
- [x] #5 
- [ ] #6 Sessions and Authentication
- [ ] #7 Refactoring Techniques
- [ ] #8 Meet Composer
